spring:
  application:
    name: resource-server
  datasource:
    url: jdbc:h2:file:~/resource-server-poc;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    generate-ddl: true

  jersey:
    application-path: /api

server:
  port: 8080